"""
Chess analysis utilities for player fairness evaluation.

This module provides tools for:
- Fetching games from chess.com API
- Parsing PGN files
- Analyzing positions with Stockfish
- Calculating centipawn loss metrics
"""

from .engine import (
    EngineAnalyzer,
    MultiDepthResult,
    DepthTransition,
    DEFAULT_MULTI_DEPTHS,
    PIECE_VALUES,
    SIGNIFICANT_EVAL_CHANGE,
    calculate_material_score,
    # Engine complexity heuristics
    EngineSearchMetrics,
    GapMetricResult,
    PositionComplexityHeuristics,
    calculate_eval_volatility,
    estimate_branching_factor,
    categorize_complexity,
    calculate_complexity_heuristics,
)
from .games import fetch_games, fetch_archives, get_last_game_date, parse_pgn_file, find_last_book_move, find_last_book_move_fast
from .metrics import (
    calculate_centipawn_loss,
    calculate_acpl,
    calculate_game_accuracy,
    calculate_game_accuracy_simple,
    calculate_move_accuracy,
    calculate_move_accuracy_from_cpl,
    centipawns_to_win_percent,
    mate_to_centipawns,
    eval_to_centipawns,
    calculate_acpl_by_position,
    extract_position_data,
    classify_position,
    # Move classification functions
    classify_move_by_cpl,      # Simple CPL-based: Best/Excellent/Good/Inaccuracy/Mistake/Blunder
    classify_move,             # CPL + position context: adds Critical Mistake/Critical Blunder/Missed Win
    classify_move_by_accuracy, # Win% accuracy-based (Lichess style)
    classify_advantage,
    analyze_errors_by_advantage,
)
from .fragility import (
    calculate_fragility,
    calculate_fragility_simple,
    build_interaction_graph,
    calculate_betweenness_centrality,
    # New fragility trend/distance functions
    FragilityTrend,
    FragilityAnalysis,
    calculate_game_fragility,
    get_fragility_trend,
    is_pre_fragility_peak,
)
from .openings import (
    OpeningBook,
    OpeningInfo,
    get_opening_book,
    find_last_book_ply,
    calculate_distance_from_book,
    classify_opening,
)
from .position_assessment import (
    # Data classes
    StockfishMetrics,
    Maia2Metrics,
    TrapInfo,
    StockfishMoveDistribution,
    PositionalAssessment,
    PositionAssessmentResult,
    # Constants
    MATERIAL_VALUES,
    # Functions
    calculate_pure_material,
    calculate_raw_branching_factor,
    calculate_brute_force_branching,
    detect_traps_in_candidates,
    check_trickiness,
    get_tablebase_status,
    assess_position,
    assessment_to_dict,
)
from .complexity import (
    calculate_complexity,
    calculate_complexity_fast,
    analyze_position_complexity_batch,
    ComplexityResult,
)
from .time_analysis import (
    extract_clock_times,
    analyze_time_patterns,
    detect_bot_patterns,
    merge_time_with_positions,
    calculate_time_complexity_correlation,
    TimeControl,
    # New time classification
    classify_time_spent,
    analyze_time_distribution,
)
from .maia2_analysis import (
    analyze_position_maia2,
    analyze_game_maia2,
    calculate_humanness_score,
    get_surprising_moves,
    compare_to_stockfish,
    Maia2Result,
)
from .regan_analysis import (
    analyze_game_regan,
    analyze_multiple_games_regan,
    calculate_partial_credit,
    calculate_z_score,
    compare_to_expected,
    get_expected_move_match_rate,
    ReganAnalysisResult,
    SuspiciousPosition,
    identify_suspicious_positions,
    get_regan_key_positions,
    calculate_position_difficulty,
)
from .themes import (
    TacticalTheme,
    PositionalTheme,
    ThemeDetectionResult,
    detect_fork,
    detect_pin,
    detect_skewer,
    detect_discovered_attack,
    detect_discovered_check,
    detect_double_check,
    detect_hanging_piece,
    detect_back_rank_mate_threat,
    detect_sacrifice,
    detect_advanced_pawn,
    detect_exposed_king,
    detect_endgame_type,
    analyze_position_themes,
    analyze_move_themes,
    get_all_theme_names,
)
from .game_phase import (
    GamePhase,
    GamePhaseInfo,
    detect_game_phase,
    detect_game_phase_detailed,
    get_phase_transitions,
    analyze_game_phases,
    count_major_minor_pieces,
    calculate_mixedness,
    is_endgame,
    is_opening,
)
from .tablebase import (
    TablebaseResult,
    TablebaseMoveCheck,
    TablebaseClient,
    probe_tablebase,
    check_tablebase_move,
    is_tablebase_position,
    analyze_endgame_accuracy,
    # New tablebase consistency
    TablebaseConsistencyReport,
    analyze_tablebase_consistency,
)
from .dataset import (
    # Data classes
    GameMetadata,
    PositionFeatures,
    EloAnalysis,
    ResultPatterns,
    TerminationPatterns,
    GameFeatures,
    EloRangeStats,
    # Game metadata
    extract_game_metadata,
    parse_time_control,
    determine_resolution,
    # Position features
    extract_position_features,
    extract_game_positions,
    calculate_material,
    # Dataset building
    build_game_dataset,
    build_position_dataset,
    build_opening_book,
    aggregate_game_features,
    aggregate_all_games,
    # Elo & result analysis
    analyze_elo_patterns,
    analyze_result_patterns,
    analyze_termination_patterns,
    # Save/load
    save_dataset_parquet,
    save_opening_book,
    load_dataset_parquet,
    # New opponent segment analysis
    EloSegmentStats,
    calculate_expected_win_rate,
    analyze_opponent_segments,
    # New game feature extraction
    extract_game_features,
    segment_games_by_elo_range,
    categorize_fragility,
    categorize_material_trajectory,
)
from .visualization import (
    # SVG board rendering
    render_position,
    render_key_position,
    display_key_position,
    find_key_positions,
    MoveArrow,
    COLORS,
    SQUARE_COLORS,
)
from .caching import (
    # Data structures
    TimeClassCacheState,
    CacheState,
    FetchPlan,
    OpponentProfile,
    # Opponent cache
    get_shared_opponent_cache_path,
    migrate_opponent_cache_if_needed,
    init_opponent_cache,
    get_cached_opponent_profile,
    save_opponent_profile_to_cache,
    # Game cache
    get_cache_path,
    load_cached_games_v2,
    analyze_cache_state,
    build_fetch_plan,
    merge_games,
    save_cache_with_metadata,
    query_cache_filtered,
    extract_opponents_from_games,
)
from .baseline import (
    # Data structures
    FrequentOpponent,
    GameSession,
    # API functions
    fetch_player_profile,
    batch_fetch_opponent_profiles,
    is_banned_account,
    # Game analysis
    extract_opponent_from_game,
    split_games_by_opponent_trust,
    analyze_frequent_opponents,
    analyze_timeout_patterns,
    analyze_banned_opponent_games,
    limit_games_per_time_class,
    analyze_openings_by_eco,
    # Session detection
    detect_sessions,
    assign_session_ids_to_games,
    analyze_session_patterns,
    DEFAULT_SESSION_GAP_MINUTES,
    # Baseline generation
    generate_player_baseline,
    generate_combined_baseline,
)
from .glicko2 import (
    # Data classes
    Glicko2Rating,
    Glicko2Result,
    RatingHistory,
    ImprovementAnalysis,
    # Core functions
    calculate_rating_period,
    calculate_glicko2,
    track_rating_over_time,
    # Analysis functions
    analyze_rating_improvement,
    correlate_with_regan_zscore,
    # Constants
    DEFAULT_RATING,
    DEFAULT_RD,
    DEFAULT_VOLATILITY,
    DEFAULT_TAU,
)
from .engine_cache import (
    # Data structures
    PositionEval,
    MoveEval,
    # Cache classes
    PositionEvalCache,
    MoveEvalsCache,
    GapMetricCache,
    CachedEngineAnalyzer,
    # Utilities
    normalize_fen,
    make_cache_key,
    get_engine_version,
    clear_cache,
    DEFAULT_CACHE_DIR,
)

__all__ = [
    # Engine analysis
    "EngineAnalyzer",
    "MultiDepthResult",
    "DepthTransition",
    "DEFAULT_MULTI_DEPTHS",
    "PIECE_VALUES",
    "SIGNIFICANT_EVAL_CHANGE",
    "calculate_material_score",
    # Engine complexity heuristics
    "EngineSearchMetrics",
    "GapMetricResult",
    "PositionComplexityHeuristics",
    "calculate_eval_volatility",
    "estimate_branching_factor",
    "categorize_complexity",
    "calculate_complexity_heuristics",
    # Games
    "fetch_games",
    "fetch_archives",
    "get_last_game_date",
    "parse_pgn_file",
    "find_last_book_move",
    "find_last_book_move_fast",
    "calculate_centipawn_loss",
    "calculate_acpl",
    "calculate_game_accuracy",
    "calculate_game_accuracy_simple",
    "calculate_move_accuracy",
    "calculate_move_accuracy_from_cpl",
    "centipawns_to_win_percent",
    "mate_to_centipawns",
    "eval_to_centipawns",
    "calculate_acpl_by_position",
    "extract_position_data",
    "classify_position",
    "classify_move_by_cpl",
    "classify_move",
    "calculate_fragility",
    "calculate_fragility_simple",
    "build_interaction_graph",
    "calculate_betweenness_centrality",
    # Fragility trend/distance
    "FragilityTrend",
    "FragilityAnalysis",
    "calculate_game_fragility",
    "get_fragility_trend",
    "is_pre_fragility_peak",
    # Openings
    "OpeningBook",
    "OpeningInfo",
    "get_opening_book",
    "find_last_book_ply",
    "calculate_distance_from_book",
    "classify_opening",
    # Position assessment
    "StockfishMetrics",
    "Maia2Metrics",
    "TrapInfo",
    "StockfishMoveDistribution",
    "PositionalAssessment",
    "PositionAssessmentResult",
    "MATERIAL_VALUES",
    "calculate_pure_material",
    "calculate_raw_branching_factor",
    "calculate_brute_force_branching",
    "detect_traps_in_candidates",
    "check_trickiness",
    "get_tablebase_status",
    "assess_position",
    "assessment_to_dict",
    "calculate_complexity",
    "calculate_complexity_fast",
    "analyze_position_complexity_batch",
    "ComplexityResult",
    "extract_clock_times",
    "analyze_time_patterns",
    "detect_bot_patterns",
    "merge_time_with_positions",
    "calculate_time_complexity_correlation",
    "TimeControl",
    "analyze_position_maia2",
    "analyze_game_maia2",
    "calculate_humanness_score",
    "get_surprising_moves",
    "compare_to_stockfish",
    "Maia2Result",
    "analyze_game_regan",
    "analyze_multiple_games_regan",
    "calculate_partial_credit",
    "calculate_z_score",
    "compare_to_expected",
    "get_expected_move_match_rate",
    "ReganAnalysisResult",
    "SuspiciousPosition",
    "identify_suspicious_positions",
    "get_regan_key_positions",
    "calculate_position_difficulty",
    # Theme detection
    "TacticalTheme",
    "PositionalTheme",
    "ThemeDetectionResult",
    "detect_fork",
    "detect_pin",
    "detect_skewer",
    "detect_discovered_attack",
    "detect_discovered_check",
    "detect_double_check",
    "detect_hanging_piece",
    "detect_back_rank_mate_threat",
    "detect_sacrifice",
    "detect_advanced_pawn",
    "detect_exposed_king",
    "detect_endgame_type",
    "analyze_position_themes",
    "analyze_move_themes",
    "get_all_theme_names",
    # Game phase detection
    "GamePhase",
    "GamePhaseInfo",
    "detect_game_phase",
    "detect_game_phase_detailed",
    "get_phase_transitions",
    "analyze_game_phases",
    "count_major_minor_pieces",
    "calculate_mixedness",
    "is_endgame",
    "is_opening",
    # Tablebase
    "TablebaseResult",
    "TablebaseMoveCheck",
    "TablebaseClient",
    "probe_tablebase",
    "check_tablebase_move",
    "is_tablebase_position",
    "analyze_endgame_accuracy",
    # Dataset building
    "GameMetadata",
    "PositionFeatures",
    "EloAnalysis",
    "ResultPatterns",
    "TerminationPatterns",
    "extract_game_metadata",
    "parse_time_control",
    "determine_resolution",
    "extract_position_features",
    "extract_game_positions",
    "calculate_material",
    "build_game_dataset",
    "build_position_dataset",
    "build_opening_book",
    "aggregate_game_features",
    "aggregate_all_games",
    "analyze_elo_patterns",
    "analyze_result_patterns",
    "analyze_termination_patterns",
    "save_dataset_parquet",
    "save_opening_book",
    "load_dataset_parquet",
    # New metrics functions
    "classify_move_by_accuracy",
    "classify_advantage",
    "analyze_errors_by_advantage",
    # New time functions
    "classify_time_spent",
    "analyze_time_distribution",
    # New tablebase functions
    "TablebaseConsistencyReport",
    "analyze_tablebase_consistency",
    # New opponent segment functions
    "EloSegmentStats",
    "calculate_expected_win_rate",
    "analyze_opponent_segments",
    # New game feature extraction
    "GameFeatures",
    "EloRangeStats",
    "extract_game_features",
    "segment_games_by_elo_range",
    "categorize_fragility",
    "categorize_material_trajectory",
    # Visualization
    "render_position",
    "render_key_position",
    "display_key_position",
    "find_key_positions",
    "MoveArrow",
    "COLORS",
    "SQUARE_COLORS",
    # Caching
    "TimeClassCacheState",
    "CacheState",
    "FetchPlan",
    "OpponentProfile",
    "get_shared_opponent_cache_path",
    "migrate_opponent_cache_if_needed",
    "init_opponent_cache",
    "get_cached_opponent_profile",
    "save_opponent_profile_to_cache",
    "get_cache_path",
    "load_cached_games_v2",
    "analyze_cache_state",
    "build_fetch_plan",
    "merge_games",
    "save_cache_with_metadata",
    "query_cache_filtered",
    "extract_opponents_from_games",
    # Baseline generation
    "FrequentOpponent",
    "GameSession",
    "fetch_player_profile",
    "batch_fetch_opponent_profiles",
    "is_banned_account",
    "extract_opponent_from_game",
    "split_games_by_opponent_trust",
    "analyze_frequent_opponents",
    "analyze_timeout_patterns",
    "analyze_banned_opponent_games",
    "limit_games_per_time_class",
    "analyze_openings_by_eco",
    "generate_player_baseline",
    "generate_combined_baseline",
    # Session detection
    "detect_sessions",
    "assign_session_ids_to_games",
    "analyze_session_patterns",
    "DEFAULT_SESSION_GAP_MINUTES",
    # Glicko-2 rating system
    "Glicko2Rating",
    "Glicko2Result",
    "RatingHistory",
    "ImprovementAnalysis",
    "calculate_rating_period",
    "calculate_glicko2",
    "track_rating_over_time",
    "analyze_rating_improvement",
    "correlate_with_regan_zscore",
    "DEFAULT_RATING",
    "DEFAULT_RD",
    "DEFAULT_VOLATILITY",
    "DEFAULT_TAU",
    # Engine evaluation cache
    "PositionEval",
    "MoveEval",
    "PositionEvalCache",
    "MoveEvalsCache",
    "GapMetricCache",
    "CachedEngineAnalyzer",
    "normalize_fen",
    "make_cache_key",
    "get_engine_version",
    "clear_cache",
    "DEFAULT_CACHE_DIR",
]
